import { getBankTransferEnvironment } from "@/config/environment";

/**
 * VietQR bank transfer. There is no provider API to call: the customer scans
 * the QR (or copies the account) into their own banking app and the operator
 * confirms the credit from the payments console. Everything here is therefore
 * derived from deployment configuration plus the order itself.
 */
export type BankTransferConfig = {
  bankId: string;
  accountNo: string;
  accountName: string;
};

export type BankTransferInstruction = BankTransferConfig & {
  amountVnd: number;
  orderNumber: string;
  /** What the customer must type into the transfer reference field. */
  transferContent: string;
  qrImageUrl: string;
};

const VIETQR_IMAGE_ORIGIN = "https://img.vietqr.io/image";
const VIETQR_TEMPLATE = "compact2";

/**
 * The configured receiving account, or null when the deployment has not
 * configured one. Checkout hides the bank-transfer option in that case instead
 * of promising an account it cannot print.
 */
export function readBankTransferConfig(): BankTransferConfig | null {
  try {
    const environment = getBankTransferEnvironment();
    return {
      accountName: environment.BANK_TRANSFER_ACCOUNT_NAME.trim(),
      accountNo: environment.BANK_TRANSFER_ACCOUNT_NO.trim(),
      bankId: environment.BANK_TRANSFER_BANK_ID.trim(),
    };
  } catch {
    return null;
  }
}

/**
 * `https://img.vietqr.io/image/<BANK_ID>-<ACCOUNT_NO>-compact2.png?amount=…`
 * with the order number as the transfer content. The image is generated by
 * VietQR from the account parameters, so no dependency and no server call are
 * needed to show it.
 */
export function buildVietQrImageUrl(
  input: BankTransferConfig & { amountVnd: number; transferContent: string },
): string {
  const query = new URLSearchParams({
    amount: String(input.amountVnd),
    addInfo: input.transferContent,
    accountName: input.accountName,
  });
  return `${VIETQR_IMAGE_ORIGIN}/${input.bankId}-${input.accountNo}-${VIETQR_TEMPLATE}.png?${query.toString()}`;
}

/** Null when the deployment has no receiving account to show. */
export function buildBankTransferInstruction(input: {
  amountVnd: number;
  orderNumber: string;
  config?: BankTransferConfig | null;
}): BankTransferInstruction | null {
  const config = input.config ?? readBankTransferConfig();
  if (!config) return null;
  return {
    ...config,
    amountVnd: input.amountVnd,
    orderNumber: input.orderNumber,
    transferContent: input.orderNumber,
    qrImageUrl: buildVietQrImageUrl({
      ...config,
      amountVnd: input.amountVnd,
      transferContent: input.orderNumber,
    }),
  };
}
